safety_limiter_node:
  ros__parameters:
    base_frame: base_link
    slowdown_ratio: 0.45
    collision_points_threshold_in_polygon: 6
    scan_timeout: 1.0
    robot_radius: 0.5
    length: 0.5
    scale: 1.5
    slowdown_polygon: [-0.4, 0.5, -0.4, -0.5, 0.7, -0.5, 0.7, 0.5]
    stop_polygon: [-0.3, 0.3, -0.3, -0.3, 0.5, -0.3, 0.5, 0.3]
