safety_limiter_node:
  ros__parameters:
    hz: 10.0
    base_frame: base_link
    use_radius_foot_print: false
    predict_step: 10
    predict_time: 2.0
    margin: 0.2
    alpha: 0.5
    foot_print_radius: 0.5
    foot_print: [-0.3, 0.3, -0.3, -0.3, 0.3, -0.3, 0.3, 0.3]
