navyu_global_costmap_node:
  ros__parameters:
    update_frequency: 1.0
    base_frame_id: base_link
    map_frame_id: map
    plugins: [static_layer, dynamic_layer, inflation_layer]
    inflation_layer:
      inflation_radius: 0.55
      robot_radius: 0.22
    static_layer:
      map_topic: map
    dynamic_layer:
      scan_topic: scan
      global_frame: map
      min_laser_range: 0.0
      max_laser_range: 5.0

navyu_global_planner_node:
  ros__parameters:
    map_frame: map
    base_frame: base_link
    displacement_threshold: 5.0
    lethal_cost_threshold: 30.0

navyu_path_tracker_node:
  ros__parameters:
    map_frame: map
    base_frame: base_link
    update_frequency: 100.0
    limit_v_speed: 0.5
    limit_w_speed: 1.0
    yaw_tolerance: 0.07
    gain: 0.1 # to update look_ahead_distance from velocity
    look_ahead_const: 0.3

navyu_safety_limiter_node:
  ros__parameters:
    base_frame: base_link
    slowdown_ratio: 0.45
    collision_points_threshold_in_polygon: 6
    scan_timeout: 1.0
    robot_radius: 0.5
    length: 0.5
    scale: 1.5
    slowdown_polygon: [-0.4, 0.5, -0.4, -0.5, 0.7, -0.5, 0.7, 0.5]
    stop_polygon: [-0.3, 0.3, -0.3, -0.3, 0.5, -0.3, 0.5, 0.3]
